# SPDX-License-Identifier: PMPL-1.0-or-later
name = "FormBDAnalytics"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Hyperpolymath <hyperpolymath@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.10"
