# SPDX-License-Identifier: PMPL-1.0-or-later
[package]
name = "formdb_nif"
version = "1.0.0"
edition = "2021"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]

[lib]
name = "formdb_nif"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.35"
